id: I2F422E36
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:49:33+00:00'
last_modified: '2022-06-08T09:19:28.918947+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ65562
  title: འཇིགས་བྱེད་དཔའ་བོ་གཅིག་པའི་ཞི་བའི་སྦྱིན་སྲེག་གི་ཆོ་ག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    14B2:
      image_group_id: I4CZ65601
      title: ''
      total_pages: 42
      order: 1
      base_file: 14B2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
